#-------------------------------------------------------------------------------
#
#-------------------------------------------------------------------------------

resolver: lts-16.5
#resolver: nightly-2020-08-26

#extra-deps:
#  - dlist-1.0
