#-------------------------------------------------------------------------------
# ZENACY: Refine
#
# Copyright (C) Zenacy Reader Technologies LLC
#-------------------------------------------------------------------------------

resolver: lts-16.5
