#-------------------------------------------------------------------------------
#
#-------------------------------------------------------------------------------

#resolver: nightly-2022-11-26
resolver: lts-20.1

#nix:
#  enable: true
#

