#-------------------------------------------------------------------------------
#
#-------------------------------------------------------------------------------

resolver: lts-18.12

#nix:
#  enable: true
#
