#-------------------------------------------------------------------------------
#
#-------------------------------------------------------------------------------

resolver: nightly-2023-05-30
# resolver: lts-20.22

#nix:
#  enable: true
#
