#-------------------------------------------------------------------------------
#
#-------------------------------------------------------------------------------

resolver: lts-19.33
#resolver: nightly-2022-11-21

#nix:
#  enable: true
#
