#-------------------------------------------------------------------------------
#
#-------------------------------------------------------------------------------

resolver: nightly-2022-12-05
#resolver: lts-20.1

#nix:
#  enable: true
#

